### REGISTER
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Usuário Vendedor",
  "email": "vend@ex.com",
  "password": "123",
  "role": "VENDEDOR",
  "addresses": [
  ]
}




### AUTHENTICATION
# @name postAuthentication
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email": "vend@ex.com",
  "password": "123"
}

@auth_token = {{postAuthentication.response.body.token}};
# > {% client.global.set("auth_token", response.body.token); %}


### BUSCA PAGINADA DE USUÁRIOS
GET  http://localhost:8080/auth/user/3
Authorization: Bearer {{auth_token}}


### Alterar dados do usuário
PUT http://localhost:8080/auth/user/4
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "teste alterado",
  "addresses": [
    {
      "street": "Rua 1000",
      "number": "asd",
      "complement": "AP",
      "district": "Centro",
      "city": "Cascavel",
      "state": "PR",
      "postalCode": "854400000",
      "addressType": "1"
    }
  ]
}

### DELETAR USUÁRIO
DELETE http://localhost:8080/auth/user/8
Authorization: Bearer {{auth_token}}

### GET ENDEREÇOS
GET http://localhost:8080/auth/user/1/address
Authorization: Bearer {{auth_token}}

### GET ENDEREÇO
GET http://localhost:8080/auth/user/1/address/1
Authorization: Bearer {{auth_token}}

### UPDATE ENDEREÇO
PUT http://localhost:8080/auth/user/1/address/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "street": "Avenida Brasil",
  "number": "2450",
  "complement": "Apartmento 100",
  "district": "Centro",
  "city": "Cascavel",
  "state": "PR",
  "postalCode": "80000000",
  "addressType": "0"
}

### CADASTRAR ENDEREÇO
POST http://localhost:8080/auth/user/1/address
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "street": "Avenida Brasil",
  "number": "2450",
  "complement": "Apartmento 100",
  "district": "Centro",
  "city": "Cascavel",
  "state": "PR",
  "postalCode": "80000000",
  "addressType": "0"
}

### DELETAR ENDEREÇO
DELETE http://localhost:8080/auth/user/1/address/2
Authorization: Bearer {{auth_token}}