### REGISTER
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "Comprador",
  "email": "comprador@ex.com",
  "password": "123",
  "role": "COMPRADOR"
}




### AUTHENTICATION
# @name postAuthentication
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email": "comprador@ex.com",
  "password": "123"
}

@auth_token = {{postAuthentication.response.body.token}};
# > {% client.global.set("auth_token", response.body.token); %}


### BUSCA PAGINADA DE USUÁRIOS
GET  http://localhost:8080/auth/user/5
Authorization: Bearer {{auth_token}}


### Alterar dados do usuário
PUT http://localhost:8080/auth/user/4
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "teste alterado",
  "addresses": [
    {
      "street": "Rua 1000",
      "number": "asd",
      "complement": "AP",
      "district": "Centro",
      "city": "Cascavel",
      "state": "PR",
      "postalCode": "854400000",
      "addressType": "1"
    }
  ]
}

### DELETAR USUÁRIO
DELETE http://localhost:8080/auth/user/5
Authorization: Bearer {{auth_token}}