### REGISTER
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "João das Coves",
  "email": "couves@example.com",
  "password": "123456",
  "role": "VENDEDOR",
  "addresses": [
    {
      "street": "Rua Teste",
      "number": "123",
      "complement": "Casa",
      "district": "Centro",
      "city": "Curitiba",
      "state": "PR",
      "postalCode": "80000000",
      "addressType": "1"
    },
    {
      "street": "Rua Teste 2",
      "number": "456",
      "complement": "Apartamento",
      "district": "Centro",
      "city": "Curitiba",
      "state": "PR",
      "postalCode": "80000000",
      "addressType": "0"
    }
  ]
}




### AUTHENTICATION
# @name postAuthentication
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email": "couves@example.com",
  "password": "123456"
}

@auth_token = {{postAuthentication.response.body.token}};
# > {% client.global.set("auth_token", response.body.token); %}


### BUSCA PAGINADA DE USUÁRIOS
GET http://localhost:8080/auth/user/3
Authorization: Bearer {{auth_token}}

### Alterar dados do usuário
PUT http://localhost:8080/auth/user/3
Content-Type: application/json

{
  "name": "João das Coves",
  "email": "couves@example.com",
  "role": "COMPRADOR",
  "addresses": [
    {
      "street": "Rua 0",
      "number": "123",
      "complement": "Casa",
      "district": "Centro",
      "city": "Curitiba",
      "state": "PR",
      "postalCode": "80000000",
      "addressType": "1"
    }
  ]
}


